# Generated by Django 5.1 on 2024-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_service_code",
                    models.CharField(
                        blank=True,
                        db_column="地方医疗服务项目代码",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "local_service_name",
                    models.CharField(
                        blank=True,
                        db_column="地方医疗服务项目名称",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project_content",
                    models.CharField(
                        blank=True, db_column="项目内涵", max_length=255, null=True
                    ),
                ),
                (
                    "except_content",
                    models.CharField(
                        blank=True, db_column="除外内容", max_length=255, null=True
                    ),
                ),
                (
                    "pricing_unit",
                    models.CharField(
                        blank=True, db_column="计价单位", max_length=255, null=True
                    ),
                ),
                (
                    "project_description",
                    models.CharField(
                        blank=True, db_column="项目说明", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "medical_service",
                "managed": False,
            },
        ),
    ]
